"""Integration test: PrintPal's /slice drives the local PrintMCP OrcaSlicer tool.

This is a REAL end-to-end test of the cross-repo seam:
  PrintPal cmd_slice  ->  PrintMCP orca_slice_model (local checkout)
    ->  OrcaSlicer CLI  ->  G-code  ->  G-code BLOB in PrintPal DB.

It imports printmcp from the sibling PrintMCP checkout (``../PrintMCP/src``),
so both repos must live side by side. It requires OrcaSlicer installed (native or
Flatpak); on machines without it the test is skipped. Mark ``integration`` so it can
be deselected with ``-m "not integration"``.
"""

from __future__ import annotations

import asyncio
import struct
import sys
from pathlib import Path

import pytest

# Make the sibling PrintMCP source importable (or fall back to an installed printmcp).
# tests/ -> PrintPal/ -> <Coding Projects>/ ; PrintMCP is a sibling of PrintPal.
_PRINTMCP_SRC = Path(__file__).resolve().parents[2] / "PrintMCP" / "src"
if _PRINTMCP_SRC.is_dir() and str(_PRINTMCP_SRC) not in sys.path:
    sys.path.insert(0, str(_PRINTMCP_SRC))

pytest.importorskip("printmcp.config", reason="PrintMCP checkout not found next to PrintPal")
pytest.importorskip("printmcp.orca", reason="PrintMCP checkout has no orca module")

from printmcp.config import get_orca_paths  # noqa: E402  (after importorskip + sys.path shim)
from printmcp.orca import orca_slice_model  # noqa: E402

from printpal import db as pp_db  # noqa: E402
from printpal.commands import thing as pp_thing  # noqa: E402


def _write_cube_stl(path) -> None:
    """Write a valid closed 20mm binary cube STL (12 triangles)."""
    vertices = [
        (0, 0, 0),
        (20, 0, 0),
        (20, 20, 0),
        (0, 20, 0),
        (0, 0, 20),
        (20, 0, 20),
        (20, 20, 20),
        (0, 20, 20),
    ]
    faces = [
        (0, 3, 2),
        (0, 2, 1),
        (4, 5, 6),
        (4, 6, 7),
        (0, 1, 5),
        (0, 5, 4),
        (2, 3, 7),
        (2, 7, 6),
        (1, 2, 6),
        (1, 6, 5),
        (0, 4, 7),
        (0, 7, 3),
    ]

    def nrm(a, b, c):
        import math

        ux, uy, uz = [b[i] - a[i] for i in range(3)]
        vx, vy, vz = [c[i] - a[i] for i in range(3)]
        n = (uy * vz - uz * vy, uz * vx - ux * vz, ux * vy - uy * vx)
        length = math.sqrt(sum(x * x for x in n)) or 1
        return tuple(x / length for x in n)

    with open(path, "wb") as fh:
        fh.write(b"\0" * 80)
        fh.write(struct.pack("<I", len(faces)))
        for f in faces:
            a, b, c = [vertices[i] for i in f]
            fh.write(struct.pack("<12fH", *nrm(a, b, c), *[c_ for v in (a, b, c) for c_ in v], 0))


def _orca_available() -> bool:
    try:
        get_orca_paths()
        return True
    except (FileNotFoundError, OSError, RuntimeError):
        return False


class _Tool:
    """Minimal stand-in for an MCP tool object: has .name and .forward(), and
    drives the (async) PrintMCP coroutine to completion synchronously."""

    def __init__(self, name, coro_fn):
        self.name = name
        self._coro_fn = coro_fn

    def forward(self, **kwargs):
        return asyncio.run(self._coro_fn(**kwargs))


@pytest.mark.integration
def test_slice_via_orca_end_to_end(tmp_path, monkeypatch):
    if not _orca_available():
        pytest.skip("OrcaSlicer not available on this machine")

    # Isolate the app DB so we don't touch the user's ~/.printpal database.
    monkeypatch.setattr(pp_db, "DB_PATH", tmp_path / "printpal.db")
    pp_db.init_db()

    # Seed a real model thing into the isolated DB.
    stl = tmp_path / "cube.stl"
    _write_cube_stl(stl)
    model_bytes = stl.read_bytes()
    thing_id = pp_db.insert_thing(
        thingiverse_id=None,
        name="integration-cube",
        creator=None,
        license=None,
        url=None,
        file_name="cube.stl",
        file_size=len(model_bytes),
        file_data=model_bytes,
        file_type="model",
        status="downloaded",
    )

    tools = [_Tool("orca_slice_model", orca_slice_model)]

    # Drive the real /slice command; --slicer orca forces the Orca backend.
    pp_thing.cmd_slice([str(thing_id), "--slicer", "orca"], tools)

    # A gcode thing derived from the model must now exist in the DB.
    gcodes = [t for t in pp_db.list_things() if t["file_type"] == "gcode"]
    assert gcodes, "expected a gcode thing after slicing"
    g = gcodes[0]
    assert g["sliced_from"] == thing_id
    # list_things() omits the BLOB; fetch the full row to verify the G-code bytes.
    full = pp_db.get_thing(g["id"])
    assert full is not None
    data = full["file_data"]
    assert data is not None and len(data) > 1000
    assert b"; generated by OrcaSlicer" in bytes(data[:400])
