"""Offline tests for printer presets and /slice's preset resolution.

No slicer, no network, no real ~/.printpal — every test isolates the DB by
monkeypatching db.DB_PATH to a temp file. The /slice backend-selection and
preset-resolution are exercised with stub tool objects whose forward() writes a
G-code file (so the DB insert path runs for real), capturing the kwargs.
"""

from __future__ import annotations

import pytest

from printpal import db
from printpal.commands import thing as pp_thing
from printpal.config import ORCA_DEFAULTS


@pytest.fixture()
def tmp_db(tmp_path, monkeypatch):
    """Fresh, isolated PrintPal DB for each test."""
    monkeypatch.setattr(db, "DB_PATH", tmp_path / "printpal.db")
    db.init_db()
    return tmp_path / "printpal.db"


def _seed_model(model_bytes: bytes = b"\x00" * 128):
    return db.insert_thing(
        thingiverse_id=None,
        name="m.stl",
        creator=None,
        license=None,
        url=None,
        file_name="m.stl",
        file_size=len(model_bytes),
        file_data=model_bytes,
        file_type="model",
        status="downloaded",
    )


class _StubOrcaTool:
    """Stands in for orca_slice_model: records kwargs, writes a gcode file."""

    name = "orca_slice_model"

    def __init__(self):
        self.kwargs = None

    def forward(self, **kwargs):
        self.kwargs = kwargs
        from pathlib import Path

        Path(kwargs["output_path"]).write_bytes(b"; generated by OrcaSlicer\nG1 X0\n")
        return {
            "gcode_path": kwargs["output_path"],
            "gcode_size_bytes": 40,
            "settings": {
                "machine": kwargs["machine"],
                "process": kwargs["process"],
                "filament": kwargs["filament"],
            },
            "stats": {},
        }


class _StubCuraTool:
    name = "cura_slice_model"

    def __init__(self):
        self.kwargs = None

    def forward(self, **kwargs):
        self.kwargs = kwargs
        from pathlib import Path

        Path(kwargs["output_path"]).write_bytes(b"; Cura G-code\n")
        return {
            "gcode_path": kwargs["output_path"],
            "gcode_size_bytes": 20,
            "printer": kwargs.get("printer", "?"),
            "settings": {},
            "stats": {},
        }


def _gcode_things():
    return [t for t in db.list_things() if t["file_type"] == "gcode"]


# --------------------------------------------------------------------------- #
# DB CRUD
# --------------------------------------------------------------------------- #
def test_default_printer_seeded(tmp_db):
    names = {p["name"] for p in db.list_printers()}
    assert "ender-3-pro" in names
    e3 = db.get_printer("ender-3-pro")
    assert e3 is not None
    assert e3["cura_printer"] == "creality_ender3pro"
    assert e3["orca_machine"] == ORCA_DEFAULTS["orca_machine"]


def test_upsert_and_get_case_insensitive(tmp_db):
    db.upsert_printer("Voron 2.4", cura_printer="voron24", orca_machine="Voron 2.4 0.4 nozzle")
    p = db.get_printer("voron 2.4")
    assert p is not None
    assert p["name"] == "Voron 2.4"
    assert p["cura_printer"] == "voron24"


def test_upsert_overwrites_existing(tmp_db):
    db.upsert_printer("x", orca_machine="M1")
    db.upsert_printer("X", orca_machine="M2")  # case-insensitive unique
    p = db.get_printer("x")
    assert p is not None and p["orca_machine"] == "M2"
    assert len([q for q in db.list_printers() if q["name"].lower() == "x"]) == 1


def test_delete_printer(tmp_db):
    db.upsert_printer("gone")
    assert db.delete_printer("gone") is True
    assert db.get_printer("gone") is None
    assert db.delete_printer("gone") is False


def test_use_printer_writes_settings_and_active(tmp_db):
    db.upsert_printer(
        "myprinter",
        cura_printer="my_cura",
        orca_machine="My Machine",
        orca_process="My Process",
        orca_filament="My PLA",
    )
    applied = db.use_printer("myprinter")
    assert applied is not None
    assert db.get_setting("cura_printer") == "my_cura"
    assert db.get_setting("orca_machine") == "My Machine"
    assert db.get_setting("orca_process") == "My Process"
    assert db.get_setting("orca_filament") == "My PLA"
    active = db.get_active_printer()
    assert active is not None and active["name"] == "myprinter"


def test_use_printer_unknown_returns_none(tmp_db):
    assert db.use_printer("nope") is None
    assert db.get_active_printer() is None


def test_remove_active_printer_clears_applied_settings(tmp_db, monkeypatch):
    """Removing the active printer must clear the settings it applied so /slice
    doesn't keep using a deleted printer's presets."""
    from printpal.commands import printer as pp_printer

    monkeypatch.setattr(pp_printer, "prompt_yes_no", lambda _msg: True)
    db.upsert_printer(
        "v24", orca_machine="Voron", orca_process="P", orca_filament="F", cura_printer="voron24"
    )
    db.use_printer("v24")
    assert db.get_setting("orca_machine") == "Voron"

    pp_printer.cmd_printer(["remove", "v24"])
    assert db.get_active_printer() is None
    assert db.get_setting("orca_machine") is None  # cleared, not left dangling


# --------------------------------------------------------------------------- #
# /slice: backend selection + preset resolution via active printer
# --------------------------------------------------------------------------- #
def test_slice_auto_prefers_orca(tmp_db):
    pp_thing.cmd_slice([str(_seed_model())], [_StubOrcaTool(), _StubCuraTool()])
    g = _gcode_things()
    assert g, "expected a gcode thing"
    src = db.get_thing(g[0]["id"])
    assert src is not None
    assert bytes(src["file_data"]).startswith(b"; generated by OrcaSlicer")


def test_slice_orca_uses_active_printer_presets(tmp_db):
    db.upsert_printer(
        "v24",
        orca_machine="Voron 2.4 0.4 nozzle",
        orca_process="Voron Process",
        orca_filament="Voron PLA",
    )
    db.use_printer("v24")

    tool = _StubOrcaTool()
    pp_thing.cmd_slice([str(_seed_model())], [tool])

    assert tool.kwargs is not None
    assert tool.kwargs["machine"] == "Voron 2.4 0.4 nozzle"
    assert tool.kwargs["process"] == "Voron Process"
    assert tool.kwargs["filament"] == "Voron PLA"
    # absolute extrusion default is injected
    assert tool.kwargs["overrides"]["use_relative_e_distances"] == 0


def test_slice_orca_falls_back_to_config_then_defaults(tmp_db, monkeypatch):
    # No active printer, but a config override set -> config wins over defaults.
    db.set_setting("orca_machine", "Config Machine")
    tool = _StubOrcaTool()
    pp_thing.cmd_slice([str(_seed_model())], [tool])
    assert tool.kwargs is not None
    assert tool.kwargs["machine"] == "Config Machine"

    # Fresh DB + no config: defaults win.
    db.delete_setting("orca_machine")
    tool2 = _StubOrcaTool()
    pp_thing.cmd_slice([str(_seed_model(b"\x01" * 128))], [tool2])
    assert tool2.kwargs is not None
    assert tool2.kwargs["machine"] == ORCA_DEFAULTS["orca_machine"]


def test_slice_force_cura_uses_active_printer_cura_id(tmp_db):
    db.upsert_printer("v24", cura_printer="voron24_cura")
    db.use_printer("v24")
    tool = _StubCuraTool()
    pp_thing.cmd_slice([str(_seed_model()), "--slicer", "cura"], [tool])
    assert tool.kwargs is not None
    assert tool.kwargs["printer"] == "voron24_cura"


def test_slice_cura_flag_beats_active_printer(tmp_db):
    db.upsert_printer("v24", cura_printer="voron24_cura")
    db.use_printer("v24")
    tool = _StubCuraTool()
    pp_thing.cmd_slice([str(_seed_model()), "--slicer", "cura", "--printer", "prusa_mk4"], [tool])
    assert tool.kwargs is not None
    assert tool.kwargs["printer"] == "prusa_mk4"  # explicit flag wins


# --------------------------------------------------------------------------- #
# Adhesion mapping: the unified keyword must translate to Orca's real settings
# (brim_width / raft_layers / skirt_loops), NOT a nonexistent "adhesion_type".
# --------------------------------------------------------------------------- #
def _orca_overrides_for(args):
    tool = _StubOrcaTool()
    pp_thing.cmd_slice([str(_seed_model()), "--slicer", "orca"] + args, [tool])
    assert tool.kwargs is not None
    return tool.kwargs["overrides"]


def test_orca_adhesion_brim(tmp_db):
    ov = _orca_overrides_for(["--adhesion", "brim"])
    assert ov["brim_width"] == "5"
    assert ov["skirt_loops"] == "0"
    assert "adhesion_type" not in ov  # must not leak the Cura keyword
    assert ov["use_relative_e_distances"] == 0  # still injected


def test_orca_adhesion_raft(tmp_db):
    ov = _orca_overrides_for(["--adhesion", "raft"])
    assert ov["raft_layers"] == "3"
    assert ov["skirt_loops"] == "0"
    assert ov["brim_width"] == "0"


def test_orca_adhesion_none(tmp_db):
    ov = _orca_overrides_for(["--adhesion", "none"])
    assert ov["skirt_loops"] == "0"
    assert ov["brim_width"] == "0"
    assert ov["raft_layers"] == "0"


def test_orca_infill_percent_and_supports(tmp_db):
    ov = _orca_overrides_for(["--infill", "40", "--supports"])
    assert ov["sparse_infill_density"] == "40%"  # % suffix
    assert ov["enable_support"] is True
