"""Test that the memory scanner ingests agent-invoked orca_slice_model results.

The scanner (scanner.py) walks agent memory after agent.run() and persists any
download/slice files into the things table. It must recognize orca_slice_model
the same way it recognizes cura_slice_model. Offline: uses a fake "step" and a
temp DB.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from printpal import db
from printpal.scanner import scan_for_downloads


@pytest.fixture()
def tmp_db(tmp_path, monkeypatch):
    monkeypatch.setattr(db, "DB_PATH", tmp_path / "printpal.db")
    db.init_db()
    return tmp_path


class _FakeStep:
    """Minimal stand-in for a smolagents memory step."""

    def __init__(self, step_number, code_action, action_output=None, observations=""):
        self.step_number = step_number
        self.code_action = code_action
        self.action_output = action_output
        self.observations = observations
        self.is_final_answer = False


class _FakeAgent:
    def __init__(self, steps):
        self.memory = type("M", (), {"steps": steps})()


def _seed_model_thing(tmp_path: Path):
    model = tmp_path / "cube.stl"
    model.write_bytes(b"\x00" * 100)
    return db.insert_thing(
        thingiverse_id=None,
        name="cube",
        creator=None,
        license=None,
        url=None,
        file_name="cube.stl",
        file_size=100,
        file_data=model.read_bytes(),
        file_type="model",
        status="downloaded",
    )


def test_scan_ingests_orca_slice_step(tmp_db):
    thing_id = _seed_model_thing(tmp_db)
    # Make a real gcode file on disk that the scanner will read + delete.
    gcode = Path(tmp_db) / "cube.gcode"
    gcode.write_bytes(b"; generated by OrcaSlicer\nG1 X0\n")

    result = {
        "slicer": "orcaslicer",
        "model": "cube.stl",
        "gcode_path": str(gcode),
        "gcode_size_bytes": gcode.stat().st_size,
        "settings": {"machine": "M", "process": "P", "filament": "F"},
        "stats": {"print_time": "24m 21s", "filament_m": 1.331},
    }
    step = _FakeStep(1, code_action="orca_slice_model(...)", action_output=result)
    scan_for_downloads(_FakeAgent([step]))

    gcodes = [t for t in db.list_things() if t["file_type"] == "gcode"]
    assert gcodes, "expected a gcode thing from the orca step"
    full = db.get_thing(gcodes[0]["id"])
    assert full is not None
    assert bytes(full["file_data"]).startswith(b"; generated by OrcaSlicer")
    # Scanner links it back to the source model and deletes the disk file.
    assert gcodes[0]["sliced_from"] == thing_id
    assert not gcode.exists()


def test_scan_ingests_cura_slice_step_still_works(tmp_db):
    thing_id = _seed_model_thing(tmp_db)
    gcode = Path(tmp_db) / "cube_cura.gcode"
    gcode.write_bytes(b";FLAVOR:Marlin\nG1 X0\n")
    result = {
        "printer": "creality_ender3pro",
        "model": "cube.stl",
        "gcode_path": str(gcode),
        "gcode_size_bytes": gcode.stat().st_size,
        "settings": {"layer_height": 0.2, "infill_density": 20, "supports": False},
        "stats": {},
    }
    step = _FakeStep(1, code_action="cura_slice_model(...)", action_output=result)
    scan_for_downloads(_FakeAgent([step]))
    gcodes = [t for t in db.list_things() if t["file_type"] == "gcode"]
    assert gcodes, "cura slice must still be ingested"
    assert gcodes[0]["sliced_from"] == thing_id
